Prototypical File {#file-prototype}
====================================

As stated before, in [Consistency across Files](#consistency-files), using a consistent file structure can (a) improve the quality of the code because the structure has been proven over time to facilitate good practices and (b) allow your intentions to be more clear to teammates because they are familiar with the order and intentions of the chunks.

We use the term "chunk" for a section of code because it corresponds with knitr terminology [@xie2015], and in many analysis files (as opposed to manipulation files), the chunk of our R file connects to a knitr Rmd file.

Clear Memory
------------------------------------
Before the initial chunk many of our files clear the memory of variables from previous run. This is important when developig and debugging because it prevents previous runs from contaminating subsequent runs.  However it has little effect during production; we'll look at manipulation files separately from analysis files.  

Manipulation R files are [`source`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/source.html)d with the argument `local=new.env()`.  The file is executed in a fresh environment, so there are no variables to clear.  Analysis R files are typically called from an Rmd file's `knitr::read_chunk()`, and code positioned above the first chunk is not called by knitr ^[Read more about knitr's [code externalization](https://yihui.name/knitr/demo/externalization/)].

However typically do not clear the memory in R files that are [`source`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/source.html)d in the same environment as the caller, as it will interfere with the caller's variables.

```r
rm(list = ls(all.names = TRUE))
```

Load Sources
------------------------------------

In the first true chunk, [`source`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/source.html) any R files containing global variables and functions that the current file requires.  For instance, when a team of statisticians is producing a large report containing many analysis files, we define many of the graphical elements in a single file.  This sourced file defines common color palettes and graphical functions so the cosmetics are more uniform across analyses.

Keep the chunk, even if no files are sourced.  An empty chunk is instructive to readers trying to determine if any files are sourced.

```r
# ---- load-sources ------------------------------------------------------------
base::source(file="./analysis/common/display-1.R")      # Load common graphing functions.
```

Load Packages {#load-packages}
------------------------------------

The 'load-packages' chunk declares required packages, and this is near the file's beginning for three reasons.  First, a reader scanning the file can more easily determine its dependencies when located in a single chunk.  Second, if your machine is lacking a required package, it is best to know early^[The error message "Error in library(foo) : there is no package called 'foo'" is easier to understand than "Error in bar() : could not find function 'bar'"; this also illuminate conflicts arising when two packages have a `bar()` function. See McConnell 2004 Section qqq for more about the 'fail early' principle.].  Third, this style mimics a requirement of other languages, such as declaring headers at the top of a C++ file.

As discussed in the previous [qualify all functions](#qualify-functions) section, we recommend that functions are qualified with their package (*e.g.*, `foo::bar()` instead of merely `bar()`).  Consequently, the 'load-packages' chunk calls `requireNamespace()` more frequently than `library()`.  `requireNamespace()` verifies the package is available on the local machine, but does not load it into memory; `library()` verifies the package is available, and then loads it.

`requireNamespace()` is not used in several scenarios.

1. Core packages (*e.g.*, 'base' and 'stats') are loaded by R in most default installations.  We avoid unnecessary calls like `library(stats)` because they distract from more important features.
1. Obvious dependencies are not called by `reqiureNamespace()` or `library()` for similar reasons, especially if they are not called directly.  For example 'tidyselect' is not listed when 'tidyr' is listed.
1. The "pipe" function (declared in the `magrittr' package , *i.e.*, `%>%`) is attached with `import::from(magrittr, "%>%")`.  This frequently-used function is available without qualification.
1. Our analysis files tend to use many functions in a few concentrated packages (compared to manipulation files), so conflicting function names are less common.  Typical packages used in analysis are 'ggplot2' and 'lme4'.
    

The `source`d files above may load their own packages (by calling `library()`).  It is important that the `library()` calls in this file follow the 'load-sources' chunk so that identically-named functions (in different packages) are called with the correct precedent.  Otherwise identically-named functions will conflict in the namespace with hard-to-predict results.  

http://r-pkgs.had.co.nz/namespace.html#search-path about `library()`, `requireNamespace()`, and their siblings, as well as the larger concepts such as attaching functions into the search path.

```r
# ---- load-packages -----------------------------------------------------------
import::from(magrittr, "%>%" )

requireNamespace("readr"     )
requireNamespace("tidyr"     )
requireNamespace("dplyr"     ) # Don't attach. Its function names conflict many packages (esp base, stats, and plyr)
requireNamespace("rlang"     ) # Language constucts, like quosures
requireNamespace("checkmate" ) # Asserts expected conditions requireNamespace("OuhscMunge") # remotes::install_github(repo="OuhscBbmc/OuhscMunge")
```

Declare Globals
------------------------------------

Load Data
------------------------------------

Tweak Data
------------------------------------

(Unique Content)
------------------------------------

Verify Values
------------------------------------

Specify Output Columns
------------------------------------

Save to Disk or Database
------------------------------------
