# Scratch Pad of Loose Ideas


Chapters & Sections
-----------------------

1. Architecture Priciples
    1. Encapsulation
    1. Leverage team member's strenghts & avoid weaknesses
        1. Focused code files
        1. Metadata for content experts
    1. Scales
        1. Single source & single analysis
        1. Multiple sources & multiple analyses
    1. Consistency
        1. Across Files
        1. Across Languages
        1. Across Projects
1. Prototypical File
    1. Clear Memory
    1. Load Sources
    1. Load Packages
    1. Declare Globals
    1. Load Data
    1. Tweak Data
    1. (Unique Content)
    1. Verify Values
    1. Specify Output Columns
    1. Save to Disk or Database
1. Data at Rest
    1. Data States
        1. Raw
        1. Derived
            1. Project-wide File on Repo
            1. Project-wide File on Protected File Server
            1. User-specific File on Protected File Server
            1. Project-wide Database
        1. Original
    1. Data containers
        1. csv
        1. rds
        1. SQLite
        1. Central Enterprise database
        1. Central REDCap database
        1. Containers to avoid for raw/input
            1. Proprietary like xlsx, sas7bdat
1. Patterns
    1. Ellis
    1. Arch
    1. Ferry
    1. Scribe
    1. Analysis
    1. Presentation -Static
    1. Presentation -Interactive
    1. Metadata
1. Security Private Data
    1. File-level permissions
    1. Database permissions
    1. Public & Private Repositories
        1. Scrubbing GitHub history
1. Automation
    1. Flow File in R
    1. Makefile
    1. SSIS
    1. cron Jobs & Task Scheduler
    1. sink log files
1. Scaling Up
    1. Data Storage
        1. Local File vs Conventional Database vs Redshift
        1. Usage Cases
    1. Data Processing
        1. R vs SQL
        1. R vs Spark
1. Parallel Collaboration
    1. Social Contract
        1. Issues
        1. Organized Commits & Coherent Diffs
        1. Branch & Merge Strategy
    1. Code Reviews
        1. Daily Reviews of PRs
        1. Periodic Reviews of Files
    1. Remote
        1. Headset & sharing screens
1. Documentation
    1. Team-wide
    1. Project-specific
    1. Dataset origin & structure
    1. Issues & Tasks
    1. Flow Diagrams
1. Publishing Results
    1. To Other Analysts
    1. To Researchers & Content Experts
    1. To Technical-Phobic Audiences
1. Testing, Validation, & Defensive Programming
    1. Testing Functions
    1. Defensive Programming
        1. Throwing errors
    1. Validator
        1. Benefits for Analysts
        1. Benefits for Data Collectors
1. Considerations when Selecting Tools
    1. General
        1. The Component's Goal
        1. Current Skillset of Team
        1. Desired Future Skillset of Team
        1. Skillset of Audience
    1. Languages
    1. R Packages
    1. Database
1. Tools to Consider
    1. tidyverse
    1. odbc
1. Growing a Team
    1. Recruiting
    1. Training to Data Science
        1. Starting with a Researcher
        1. Starting with a Statistician
        1. Starting with a DBA
        1. Starting with a Software Developer
    1. Bridges Outside the Team
        1. Monthly User Groups
        1. Annual Conferences
